db.url=${DB_URL}
db.schema=app
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.driver=org.postgresql.Driver

db.pool.maximum-pool-size=5
db.pool.minimum-idle=1
db.pool.connection-timeout-ms=10000
db.pool.idle-timeout-ms=600000
db.pool.max-lifetime-ms=1800000

liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
liquibase.default-schema=${db.schema}
liquibase.liquibase-schema=${db.schema}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show-sql=true
hibernate.default-schema=${db.schema}
hibernate.hbm2ddl.auto=validate

app.session.ttl-hours=24

openweather.base-url=https://api.openweathermap.org
openweather.api-key=bd130ce3-be26-4d11-9332-8cd198af7a97